import './globals.css';
import type { Metadata } from 'next';
import Footer from './Footer';
import Header from './Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className="flex flex-col w-screen text-white">  
          <Header/>
            {children}
          <Footer/> 
      </body>
    </html>
  )
}
