import './globals.css';
import type { Metadata } from 'next';
import Footer from './components/footer/Footer';
import Header from './components/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body style={{backgroundImage: "linear-gradient(to right, #434343 0%, black 100%)"}} className="flex flex-col w-screen text-white">  
          <Header/>
            {children}
          <Footer/> 
      </body>
    </html>
  )
}
